# Generated by Django 4.0.5 on 2022-06-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_doclogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddoctor',
            name='Password',
            field=models.CharField(default='1234', max_length=50),
        ),
    ]
