# Generated by Django 4.0.5 on 2022-06-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_adddoctor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
