# Generated by Django 4.0.5 on 2022-06-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='filename',
        ),
    ]
